codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

ignore:
  - OpenGL.Net/Gl.VERSION_*.cs
  - OpenGL.Net/Gl.ES_VERSION_*.cs
  - OpenGL.Net/Gl.SC_VERSION_*.cs
  - OpenGL.Net/Gl.VERSION_ES_CM_1_0.cs
  - OpenGL.Net/Egl.VERSION_*.cs
  - OpenGL.Net/Glx.VERSION_*.cs
  - OpenGL.Net/Wgl.VERSION_*.cs
  - OpenGL.Net/[\w\d]+/.*
  - OpenGL.Net/*.Vb.cs
  - OpenGL.Net.Test/Gl.VERSION_*.cs
  - OpenGL.Net.Test/*Benchmamark*.cs
